### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/ruby-bubble-sort#4]
Leave some coments if any

**Comment by Kyle-Law** [comment]
Great job @patriciachrysy ! It's amazing that you go beyond project specifications and created 3 different Bulbasaur with `loop do`, `recursion`, and pure `while loop` version. 
Among them, I'm most impressed by your `recursion` version which you push the last sorted element into a new array and return `<thearray>.reverse`. 👍 
Impressive! 💯 
![image](https://user-images.githubusercontent.com/55923773/75654015-abc83d80-5c99-11ea-9aa2-c10da82afa4e.png)

**Comment by dili021** [comment]
`def my_comment(your_project)
  if method != refactored? 
    puts "Your method could be refactored to be shorter"
  else
    puts "I like to see things done differently though, so bravo!"
  end
end
`

**Comment by nyatindopatrick** [comment]
Great job, thought a few comments:

- In bubble sort redo you're returning i instead of arr
` end
  i
end`

- In bubble sort plus you can replace the reverse by just replacing greater than (>) with less than (<) in line 5
`def bubble_sort(arr, result = [])
  if arr.length > 1
    i = 1
    while i - 1 < arr.length - 1
      arr[i - 1], arr[i] = arr[i], arr[i - 1] if arr[i - 1] < arr[i]
      i += 1
    end
    result.push(arr[arr.length - 1])
    bubble_sort(arr[0..arr.length - 2], result)
  else
    result.push(arr[0])
  end
  result
end`

**Comment by patriciachrysy** [comment]
Thank you very much for your comments guys, will close this issue now.
